Unbanned event addition
ExMod-Team/EXILED pull request #185
Opened 2024-11-19 02:21 UTC by Undid-Iridium

## Description
**Describe the changes** 
https://discord.com/channels/656673194693885975/1307441157483270207

**What is the current behavior?** (You can also link to an open issue here)
Doesn't call Unban event

**What is the new behavior?** (if this is a feature change)
It calls Unban event now

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Not exactly. Function for this behaves differently so modifying the target is not easily done without breaking change so, just focusing on whether the player should or should not be unbanned should be sufficient.

**Other information**:
Not tested

<br />

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [X] I have checked the project can be compiled
- [ ] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [X] I have checked no IL patching errors in the console

### Other
- [X] Still requires more testing

@louis1706 Clarify if this is what you meant

2024-11-19 06:01 UTC, louis1706 requested changes

2024-11-20 07:43 UTC, VALERA771 commented
I don't think that this will work cuz you specify only 1 method to patch and it may just put 2 transpilers on same method

2024-11-20 16:56 UTC, Undid-Iridium commented
Check

2024-11-22 11:41 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Events/Server/Unban.cs
> +
```suggestion
```

2024-11-22 11:42 UTC, louis1706 requested changes

2024-11-22 11:42 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Events/Server/Unban.cs
> +            var continueLabel = generator.DefineLabel();
Do not use Var

2024-12-26 01:27 UTC, louis1706 approved these changes

2025-01-05 10:20 UTC, VALERA771 approved these changes
All good if works fine

2025-01-06 10:58 UTC, merged