Meh, maybe solves it.
ExMod-Team/EXILED pull request #186
Opened 2024-11-19 06:12 UTC by Undid-Iridium

## Description
**Describe the changes** 
NPC hp bug

**What is the current behavior?** (You can also link to an open issue here)
NPC hp doesn't use exiled health stat

**What is the new behavior?** (if this is a feature change)
NPC hp is now using exiled health stat.

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Maybe

**Other information**:
https://discord.com/channels/656673194693885975/1300857604620161064

<br />

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [X] I have checked the project can be compiled
- [?] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [X] I have checked no IL patching errors in the console

### Other
- [X] Still requires more testing

2024-11-19 08:14 UTC, Misfiy requested changes
Feels like Npc class should fix it (it worked a while ago, no?)

2024-11-20 04:51 UTC, Undid-Iridium commented
> Feels like Npc class should fix it (it worked a while ago, no?)

?

2024-11-20 08:59 UTC, VALERA771 commented
Bug seems to occur only on npcs so this changes should be made to npc class, not player

2024-11-22 11:40 UTC, louis1706 commented on EXILED/Exiled.API/Features/Npc.cs
> +
```suggestion
```

2024-11-22 11:40 UTC, louis1706 commented on EXILED/Exiled.API/Features/Npc.cs
> +                }
```suggestion
                }

```

2024-11-22 11:41 UTC, louis1706 requested changes

2024-11-22 11:41 UTC, louis1706 commented on EXILED/Exiled.API/Features/Npc.cs
> +            string userId = PlayerAuthenticationManager.DedicatedId, Vector3? position = null, float PlayerHealth = float.NegativeInfinity, float PlayerMaxHealth = float.NegativeInfinity)
Fix error

2024-12-26 12:37 UTC, louis1706 commented
NPC work differently now with NW SCP:SL 14 release

2024-12-26 12:37 UTC, closed without merging