Offline mode support
ExMod-Team/EXILED pull request #19
Opened 2024-08-01 10:13 UTC by x3rt

This PR does the following:

- Executes the `Verified` event in offline-mode
- Executes PluginApi's `PlayerJoinedEvent` in offline-mode
- Adds the Player's UserId to the base-game `Player.PlayersUserIds` dictionary in offline-mode
- Prevents PluginApi's `PlayerLeftEvent` from getting executed within the ReferenceHubs' Start method. Not sure why that is even a thing in the first place as it only causes issues.

This fixes bugs such as base-game roles spawning with no items during offline-mode when using EXILED
and most (if not all) events not being called at all in offline-mode

2024-08-01 17:36 UTC, louis1706 requested changes
Nothing to say other than transpiler need comment

2024-08-01 17:36 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Generic/OfflineModeIds.cs
> +                    new CodeInstruction(OpCodes.Nop).WithLabels(skipLabel),
Need comment to explain what this transpiller does in C#

2024-08-01 17:36 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Events/Player/Verified.cs
> +                    new CodeInstruction(OpCodes.Call, Method(typeof(Verified), nameof(Verified.PlayerVerified))),
Missing comment

2024-08-01 17:36 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Generic/OfflineModeIds.cs
> +                    new CodeInstruction(OpCodes.Call, Method(typeof(OfflineModeJoin), nameof(ExecuteNwEvent))),
Same as above

2024-08-02 00:53 UTC, louis1706 approved these changes

2024-08-04 06:54 UTC, x3rt commented
No Breaking Changes btw

2024-08-04 10:22 UTC, louis1706 commented
> No Breaking Changes btw

Yes it's will be merged when an other dev boy will confirm your PR

2024-08-06 19:56 UTC, Vladislav-CS approved these changes

2024-08-06 20:59 UTC, merged