Fix not returning null
ExMod-Team/EXILED pull request #22
Opened 2024-08-01 17:03 UTC by louis1706

2024-08-01 21:04 UTC, Jesus-QC requested changes

2024-08-01 21:04 UTC, Jesus-QC commented on EXILED/Exiled.API/Features/Player.cs
> +            return new(gameObject);
```suggestion
                return player;

            return new(gameObject);
```

2024-08-02 17:44 UTC, Misfiy approved these changes

2024-08-04 09:42 UTC, IRacle1 commented
I think its not a good idea create a new player by unknown gameobject in `Get` method, is this case possible in general?
And it will cause a lot of problems, with the call of this method with a non-player gameobject

2024-08-04 13:08 UTC, IRacle1 approved these changes
kk now it make sense

2024-08-04 13:12 UTC, merged