Added Emotion Events and Player.Emontion
ExMod-Team/EXILED pull request #257
Opened 2024-11-29 00:44 UTC by Rysik5318

## Description
**Describe the changes** 

**What is the current behavior?** None

**What is the new behavior?** 
Adds the ChangingEmotion and ChangedEmotionEventArgs events.
Adds Emontion variable to the Player class.

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Other
- [ ] Still requires more testing

2024-11-29 06:47 UTC, VALERA771 approved these changes
I'll pretend I didn't see bool prefix

2024-11-29 06:47 UTC, VALERA771 commented on EXILED/Exiled.API/Features/Player.cs
> +            }
```suggestion
            set => EmotionSync.ServerSetEmotionPreset(ReferenceHub, value);
```

2024-11-30 11:32 UTC, louis1706 approved these changes

2024-12-01 12:42 UTC, louis1706 commented on EXILED/Exiled.Events/Handlers/Player.cs
> +        /// <param name="ev">The <see cref="ChangingAmmoEventArgs"/> instance.</param>
```suggestion
        /// <param name="ev">The <see cref="ChangingEmotionEventArgs"/> instance.</param>
```

2024-12-01 15:19 UTC, IRacle1 requested changes
cool!!!!!!!!

Now do this without bool prefix and postfix😈

2024-12-01 16:56 UTC, louis1706 commented
> cool!!!!!!!!
> 
> Now do this without bool prefix and postfix😈

actually Postfix is fine just bool prefix is not

2024-12-02 21:08 UTC, VALERA771 reviewed
Can you add new emoji preset setter support to transpiler?

2024-12-03 00:45 UTC, Misaka-ZeroTwo commented
https://github.com/Rysik5318/EXILED/pull/1/

2024-12-03 18:18 UTC, Rysik5318 commented
> Can you add new emoji preset setter support to transpiler?

I don't know how to make a transpiller

2024-12-04 11:28 UTC, VALERA771 approved these changes

2024-12-07 15:43 UTC, merged