Null Bug in Issue #206 Fix
ExMod-Team/EXILED pull request #284
Opened 2024-12-01 12:35 UTC by PortaDEV-DownUnder

…hecks.

## Description
**Describe the changes** 
Fixes the Issue in #206 where RoomLightControllers would be a null value sometimes, resulting in a NRE.

**What is the current behavior?** (You can also link to an open issue here)
Point to #206 

**What is the new behavior?** (if this is a feature change)
- RoomLightControllersValue in Exiled.API/Features/Room.cs will be set to a new List if its count is zero, preventing a null access.
- RoomLightControllers in Exiled.Events\Handlers\Internal\Round.cs while in the for loop to fix SCP:SL Bug 52 (https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/52)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
nope.

**Other information**:
no idea
<br />

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected
^ Unable to setup debugging at time of writing due to unity weirdness, but i haven't gotten the error.

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

2024-12-01 14:05 UTC, louis1706 requested changes

2024-12-01 14:05 UTC, louis1706 commented on EXILED/Exiled.API/Features/Room.cs
> +
Can you explain me this change because i don't see what it's does make different ?

2024-12-01 14:05 UTC, louis1706 commented on EXILED/Exiled.Events/Handlers/Internal/Round.cs
> +                    continue;
It's would be better to find why a Room have a room light controller null since that would cause issue for plugin

2024-12-12 14:58 UTC, BoltonDev commented
@PortaDEV-DownUnder can you answer review?

2024-12-26 10:29 UTC, louis1706 requested changes

2024-12-26 10:29 UTC, louis1706 commented on EXILED/Exiled.API/Features/Room.cs
> +        internal List<RoomLightController> RoomLightControllersValue { get; set; } = new();
```suggestion
        internal List<RoomLightController> RoomLightControllersValue { get; internal set; } = new();
```

2024-12-26 19:03 UTC, louis1706 commented
Should work fine now

2024-12-26 19:03 UTC, closed without merging