Additions
ExMod-Team/EXILED pull request #29
Opened 2024-08-02 19:31 UTC by Misfiy

## Description
**Describe the changes** 
* Add ``Enums::HazardType``
* Add ``Extensions::BitwiseExtensions``
* Add ``Hazard::Type``
* Add ``Hazard:Get(HazardType)``
* Add ``PrefabHelper::GetPrefab<T>(PrefabType)``
* Add ``Server::MaxTps``
* Add ``TpsCommand``

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No breaking changes made.

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [ X ] I have checked the project can be compiled
- [ ] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ X ] Still requires more testing

2024-08-02 20:07 UTC, louis1706 requested changes

2024-08-02 20:07 UTC, louis1706 commented on EXILED/Exiled.API/Features/Hazards/AmnesticCloudHazard.cs
> +        public override HazardType Type { get; } = HazardType.AmnesticCloud;
Not { get; } = but => for this

2024-08-02 20:07 UTC, louis1706 commented on EXILED/Exiled.API/Features/Hazards/SinkholeHazard.cs
> +        public override HazardType Type { get; } = HazardType.Sinkhole;
Same as above

2024-08-02 20:07 UTC, louis1706 commented on EXILED/Exiled.API/Features/Hazards/TantrumHazard.cs
> +        public override HazardType Type { get; } = HazardType.Tantrum;
Same above as

2024-08-02 20:26 UTC, louis1706 requested changes
Waiting for #17 to be merged for making more suggestions 

Use bitwise method when possible like i already said you on your previous PR

2024-08-10 08:27 UTC, Misaka-ZeroTwo reviewed
Fix conflicts

2024-08-10 10:20 UTC, louis1706 approved these changes

2024-08-10 20:25 UTC, VALERA771 approved these changes

2024-08-11 08:59 UTC, merged