Implements more patches for RemovingHandcuffs event
ExMod-Team/EXILED pull request #3
Opened 2024-07-27 18:08 UTC by Misaka-ZeroTwo

- [x] Invokes when cuffer died.
- [x] Invokes when the player is too far away from cuffer

Checked no IL patching errors.

2024-07-31 22:24 UTC, louis1706 approved these changes

2024-08-01 17:45 UTC, louis1706 commented
Do not merge because this new call could be a breaking change for some plugin

2024-08-01 21:27 UTC, Jesus-QC requested changes
Merge dev into your branch

2024-08-06 11:21 UTC, louis1706 approved these changes

2024-08-09 17:15 UTC, Misfiy approved these changes

2024-08-09 18:40 UTC, merged