Fix Armor Drop
ExMod-Team/EXILED pull request #32
Opened 2024-08-03 12:59 UTC by skyyt15

## Description
Fix one of the bugs from NW trello

**What is the current behavior?** https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/230

**What is the new behavior?** Fix the bug

**Does this PR introduce a breaking change?** No

**Other information**:

<br />

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [x] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

2024-08-03 14:37 UTC, louis1706 approved these changes

2024-08-03 19:40 UTC, louis1706 requested changes

2024-08-03 19:40 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Generic/Scp173FirstKillPatch.cs
> +            // TODO: NRE ON LEFT CLICK (KICK PLAYER) - DO NOT PUSH
need to be finish

2024-08-03 19:41 UTC, skyyt15 commented on EXILED/Exiled.Events/Patches/Generic/Scp173FirstKillPatch.cs
> +            // TODO: NRE ON LEFT CLICK (KICK PLAYER) - DO NOT PUSH
yes i know

2024-08-06 11:10 UTC, skyyt15 commented on EXILED/Exiled.Events/Patches/Generic/Scp173FirstKillPatch.cs
> +            // TODO: NRE ON LEFT CLICK (KICK PLAYER) - DO NOT PUSH
fixed

2024-08-06 14:29 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Fixes/SlownessFix.cs
> +}
```suggestion
}
```

2024-08-06 14:43 UTC, louis1706 approved these changes
If everything work it's fine

2024-08-06 17:45 UTC, Vladislav-CS requested changes
PRs should target dev branch, not master

2024-08-06 17:52 UTC, Misfiy approved these changes

2024-08-06 21:00 UTC, merged