`[EXILED::API]` Adding SpawnMice
ExMod-Team/EXILED pull request #47
Opened 2024-08-11 09:22 UTC by NotZer0Two

## Description
**Describe the changes** 
Lets people spawn rats

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

Credits to Yamato for the finding
(and the idea to add it)
<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

2024-08-11 09:51 UTC, louis1706 approved these changes

2024-08-11 23:47 UTC, VALERA771 requested changes

2024-08-11 23:47 UTC, VALERA771 commented on EXILED/Exiled.API/Features/Map.cs
> +                new OverflowException($"The mice type are from 1 to {SqueakSpawner.mice.Length}");
```suggestion
                new ArgumentOutOfRangeException($"The mice type are from 1 to {SqueakSpawner.mice.Length}");
```

Do you really want to use exception here? You can use just `Log.Error`. 
Also, just creating a new instance of exception won't stop execution of method

2024-08-12 10:46 UTC, VALERA771 commented
Can you create an enum with all mouse types?

2024-08-12 14:02 UTC, NotZer0Two commented
> Can you create an enum with all mouse types?

The mouse type is just a mouse that spawn in a different position so nothing crazy and the name how should it be named like MiceOnTopOfTheBarrel etc...?

2024-08-12 15:40 UTC, NotZer0Two commented
I don't mean that but the names for the different rats because the rats are different only by their position

2024-08-12 23:12 UTC, VALERA771 commented
Ah, okay. Then forgot about enum

2024-08-13 06:18 UTC, Misfiy approved these changes

2024-08-15 23:26 UTC, VALERA771 approved these changes

2024-08-15 23:28 UTC, merged