`[EXILED::API]` Adding MoveNetworkIdentityObject
ExMod-Team/EXILED pull request #48
Opened 2024-08-11 09:29 UTC by NotZer0Two

## Description
**Describe the changes** 
Lets the user move NetworkIdentities it can be bugged for the current culling system, in theory you can move object with a radius of 500m (Very small) and that will let them load in, could be useful for moving objects that you don't want in the facility to spawn or for example the Bowl of Candy

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

2024-08-11 09:32 UTC, louis1706 approved these changes

2024-08-18 10:34 UTC, Misfiy commented
Fix conflicts

2024-08-19 20:28 UTC, louis1706 approved these changes

2024-08-20 18:58 UTC, VALERA771 approved these changes

2024-08-20 19:03 UTC, VALERA771 requested changes
fix conflicts

2024-08-27 18:59 UTC, merged