`[EXILED::API]` Adding ScaleNetworkIdentityObject
ExMod-Team/EXILED pull request #49
Opened 2024-08-11 11:20 UTC by NotZer0Two

## Description
**Describe the changes** 
Let's you scale down or up everything that has an NetworkIdentity

![SPOILER_immagine](https://github.com/user-attachments/assets/93a6713a-3eaa-42fd-a620-88876af35613)
![immagine](https://github.com/user-attachments/assets/416fa8ce-4cfb-4261-9c1d-0c86fb8aaee9)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

2024-08-11 11:28 UTC, VALERA771 commented
I think you can use NetworkServer.Unspawn and NetworkServer.Spawn for cases when you need to move object for all players

2024-08-11 13:03 UTC, Misfiy approved these changes

2024-08-11 13:03 UTC, Misfiy commented on EXILED/Exiled.API/Extensions/MirrorExtensions.cs
> +        public static void MoveNetworkIdentityObject(this Player player, NetworkIdentity identity, Vector3 scale)
You're naming the arg scale, but it does position

2024-08-11 13:05 UTC, Misfiy requested changes

2024-08-11 13:05 UTC, Misfiy commented on EXILED/Exiled.API/Extensions/MirrorExtensions.cs
> +        public static void MoveNetworkIdentityObject(this Player player, NetworkIdentity identity, Vector3 scale)
Rename arg from scale

2024-08-11 13:05 UTC, Misfiy commented on EXILED/Exiled.API/Extensions/MirrorExtensions.cs
> +        public static void MoveNetworkIdentityObject(this NetworkIdentity identity, Vector3 scale)
Rename arg from scale

2024-08-11 13:09 UTC, NotZer0Two commented
> I think you can use NetworkServer.Unspawn and NetworkServer.Spawn for cases when you need to move object for all players. And isn't it a duplicate from your previous pr? (code is similar as I can see)

yes it is, in future i will probably do one method for everything but currently i want to them seperated when the update will be released i will do it

2024-08-11 13:29 UTC, VALERA771 commented
And is there any difference between this pr and #48?

2024-08-11 13:48 UTC, NotZer0Two commented
> And is there any difference between this pr and #48?

Yes localscale its the only differents

2024-08-11 15:32 UTC, VALERA771 commented
There is local position. Seems that you haven't edited it

2024-08-11 17:38 UTC, NotZer0Two commented
Im stupid and forgot to change the name

2024-08-11 20:46 UTC, louis1706 approved these changes

2024-08-11 23:20 UTC, VALERA771 commented
I'm about that you're still setting `localPosition` in method

2024-08-11 23:21 UTC, VALERA771 requested changes

2024-08-11 23:21 UTC, VALERA771 commented on EXILED/Exiled.API/Extensions/MirrorExtensions.cs
> +            identity.gameObject.transform.localPosition = scale;
Should be scale

2024-08-11 23:21 UTC, VALERA771 commented on EXILED/Exiled.API/Extensions/MirrorExtensions.cs
> +            identity.gameObject.transform.localPosition = scale;
Same as above

2024-08-12 15:38 UTC, Misaka-ZeroTwo commented
pls fix build errors

2024-08-13 06:18 UTC, Misfiy approved these changes

2024-08-15 23:28 UTC, VALERA771 approved these changes

2024-08-15 23:29 UTC, merged