Add a title
ExMod-Team/EXILED pull request #51
Opened 2024-08-11 13:01 UTC by IRacle1

## Description
**Describe the changes** 
1. Fixes `DoorVariant::RegisterRooms` patch, that prefix condition was created by me earlier to prevent `DoorVariant::Rooms` being broken(by basegame code rooms will be empty, when register rooms more than once), but somehow it was deleted😭 (I discovered that bug for MER doors, but Im sure it can affect regular doors(al least it was before))
2. Added new overload for `SendFakeSyncVars`, for fixing sending `null` syncvars (for example sending `null` player custom info)

**What is the current behavior?** (You can also link to an open issue here)
rooms are not registered
syncvars throw nre
😭

**What is the new behavior?** (if this is a feature change)
rooms are registered
syncvars dont throw nre
😎

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No🥲

**Other information**:
Other information
<br />

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

2024-08-11 20:43 UTC, louis1706 requested changes

2024-08-11 20:43 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Generic/DoorList.cs
> +        }
Can you il code :3333

2024-08-12 08:10 UTC, Misfiy approved these changes

2024-08-12 10:21 UTC, IRacle1 commented on EXILED/Exiled.Events/Patches/Generic/DoorList.cs
> +        }
yep

2024-08-12 18:53 UTC, louis1706 requested changes

2024-08-12 18:53 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Generic/DoorList.cs
> +            // new Generator(this)
I didn't know generator was a door :33

2024-08-12 18:53 UTC, louis1706 commented on EXILED/Exiled.Events/Patches/Generic/DoorList.cs
> +                });
More comment on what is happening there please :3

2024-08-12 19:09 UTC, IRacle1 commented on EXILED/Exiled.Events/Patches/Generic/DoorList.cs
> +            // new Generator(this)
😭😭😭

2024-08-20 19:01 UTC, VALERA771 approved these changes

2024-08-27 14:21 UTC, merged