`[Exiled::Events]` `Unbanning` and `Unbanned` events
ExMod-Team/EXILED pull request #68
Opened 2024-08-16 14:00 UTC by VALERA771

## Description
**Describe the changes** 
Adding some new events

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [ ] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [x] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

2024-08-17 09:14 UTC, louis1706 approved these changes

2024-08-18 14:37 UTC, IRacle1 requested changes

2024-08-18 14:37 UTC, IRacle1 commented on EXILED/Exiled.Events/Patches/Events/Server/Unban.cs
> +                new(OpCodes.Ldloc_S, ev.LocalIndex),
i dont see where you attach `continueLabel` 🤨
prob should be like that
```suggestion
                new(OpCodes.Callvirt, PropertyGetter(typeof(UnbanningEventArgs), nameof(UnbanningEventArgs.IsAllowed))),
                new(OpCodes.Brtrue_S, continueLabel),

                new(OpCodes.Ret),

                // id = ev.BanDetails.ToString();
                new CodeInstruction(OpCodes.Ldloc_S, ev.LocalIndex).WithLabels(continueLabel),
```

2024-08-27 14:26 UTC, louis1706 approved these changes

2024-08-27 14:26 UTC, merged