`[EXILED::EVENTS]` Adding PlayingAudioLog
ExMod-Team/EXILED pull request #69
Opened 2024-08-17 12:08 UTC by NotZer0Two

## Description
**Describe the changes** 
Adding the possibility to Disallow and Allow playing the Audio from an AudioLog

**What is the current behavior?** (You can also link to an open issue here)
None

**What is the new behavior?** (if this is a feature change)
None

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
None

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [x] I have checked the project can be compiled
- [x] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [x] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

2024-08-17 12:55 UTC, louis1706 requested changes
This colliderId is never used in the NW Method

2024-08-17 15:26 UTC, louis1706 approved these changes

2024-08-17 16:27 UTC, 6hundred9 commented
🧠💭😔😞📉😭🤔➡️🧑‍⚕️💬💊📈😌

2024-08-19 14:11 UTC, VALERA771 approved these changes

2024-08-27 18:59 UTC, merged