Adding auto assignment to pr
ExMod-Team/EXILED pull request #7
Opened 2024-07-29 21:59 UTC by VALERA771

2024-07-30 04:57 UTC, ALEXWARELLC requested changes
Please read through.

Thanks.

2024-07-30 04:57 UTC, ALEXWARELLC commented on .github/workflows/auto-assigning.yml
> +      - uses: toshimaru/auto-author-assign@v2.1.1
With the size of this GitHub Action, this should actually be moved into the labeller and rename the labeller to `pull_request_opened.yml`.

This gives the workflow file a meaningful name and compresses what is the same action into 1, easy to identify file.

2024-07-30 04:57 UTC, ALEXWARELLC commented on .github/workflows/auto-assigning.yml
> +    types: [ opened, reopened ]
No need to add a reopening trigger due to the author already being added when the Pull Request is initially created.

2024-07-30 04:57 UTC, ALEXWARELLC commented
Also, please make sure this workflow has been tested and works.

2024-07-30 09:51 UTC, VALERA771 commented
Tested (bruh where label)

2024-07-30 13:58 UTC, ALEXWARELLC approved these changes
👍

2024-07-31 22:28 UTC, louis1706 approved these changes

2024-08-01 17:54 UTC, Misaka-ZeroTwo approved these changes

2024-08-01 19:10 UTC, merged