Add round end feature
ExMod-Team/EXILED pull request #86
Opened 2024-09-01 08:06 UTC by louis1706

## Description
**Describe the changes** 

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?** (if this is a feature change)

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

<br />

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentations
<br />

## Submission checklist

- [ ] I have checked the project can be compiled
- [ ] I have tested my changes and it worked as expected

### Patches (if there are any changes related to Harmony patches)
- [ ] I have checked no IL patching errors in the console

### Other
- [ ] Still requires more testing

2024-09-02 05:30 UTC, Misaka-ZeroTwo reviewed
Please use ChatGPT or Grammarly on your docs. And properly describe your changes using the template :)

2024-09-02 17:16 UTC, VladTheCow requested changes

2024-09-02 17:16 UTC, VladTheCow commented on EXILED/Exiled.API/Features/Round.cs
> +            [Obsolete("This value is rewrited by NW every time it's used", true)]
```suggestion
            [Obsolete("This value is rewritten by NW every time it's used", true)]
```

2024-09-02 17:16 UTC, VladTheCow commented on EXILED/Exiled.Events/EventArgs/Server/RoundEndedEventArgs.cs
> +        /// Gets or sets a value indicating whether than Round Summary will be sent to all player.
```suggestion
        /// Gets or sets a value indicating whether Round Summary will be sent to all players.
```

2024-09-02 17:24 UTC, louis1706 commented
> Please use ChatGPT or Grammarly on your docs. And properly describe your changes using the template :)

Was a fast idea i wanted to put on paper i have exam this week so i don't really have time to do more rn

2024-10-19 11:05 UTC, VALERA771 approved these changes

2024-10-27 11:39 UTC, Misfiy approved these changes

2024-10-27 11:43 UTC, merged